/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View;

import org.example.Connection.ConexaoMySQL;
import org.example.DAO.DiaSemanaVoluntarioDAO;
import org.example.DAO.DoacaoDAO;
import org.example.DTO.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

/**
 *
 * @author Estella1
 */
public class TelaCadastroDoacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDoacao
     */
    public TelaCadastroDoacao() {
        initComponents();
        
        doacao_financeira.setVisible(false);
        item_material.setVisible(false);
        trabalho_voluntario.setVisible(false);
        panel_campanha.setVisible(false);
        panel_doador.setVisible(false);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowOpened(java.awt.event.WindowEvent evt) {
            carregarCampanhas(); // chama sua função            
            carregarDoadores();
        }
    });
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        slct_doacao_finaceira = new javax.swing.JRadioButton();
        slct_trabalho_volunatrio = new javax.swing.JRadioButton();
        slct_item_material = new javax.swing.JRadioButton();
        doacao_financeira = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valor_total = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        forma_pagamento = new javax.swing.JComboBox<>();
        item_material = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        estado_conservacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantidade = new javax.swing.JFormattedTextField();
        estimativa_valor = new javax.swing.JFormattedTextField();
        trabalho_voluntario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        data_inicio = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        data_final = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        domingo = new javax.swing.JCheckBox();
        segunda = new javax.swing.JCheckBox();
        terça = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        descricao_servico = new javax.swing.JScrollPane();
        txtDescricao_servico = new javax.swing.JTextPane();
        orgem_doacao = new javax.swing.JPanel();
        opc_campanha = new javax.swing.JRadioButton();
        opc_doador = new javax.swing.JRadioButton();
        panel_campanha = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboCampanha = new JComboBox<ComboAuxiliar>();
        panel_doador = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        comboDador = new JComboBox<ComboAuxiliar>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Doação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup1.add(slct_doacao_finaceira);
        slct_doacao_finaceira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slct_doacao_finaceira.setText("Doação Finaceira");
        slct_doacao_finaceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slct_doacao_finaceiraActionPerformed(evt);
            }
        });

        buttonGroup1.add(slct_trabalho_volunatrio);
        slct_trabalho_volunatrio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slct_trabalho_volunatrio.setText("Trabalho Voluntário");
        slct_trabalho_volunatrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slct_trabalho_volunatrioActionPerformed(evt);
            }
        });

        buttonGroup1.add(slct_item_material);
        slct_item_material.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slct_item_material.setText("Item Material");
        slct_item_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slct_item_materialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(slct_doacao_finaceira, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slct_trabalho_volunatrio)
                .addGap(18, 18, 18)
                .addComponent(slct_item_material)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slct_doacao_finaceira)
                    .addComponent(slct_trabalho_volunatrio)
                    .addComponent(slct_item_material))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        doacao_financeira.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doação Financeira", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Valor total:");

        jScrollPane1.setViewportView(valor_total);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Forma de Pagamento:");

        forma_pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "Crédito", "Débito", "Dinheiro" }));

        javax.swing.GroupLayout doacao_financeiraLayout = new javax.swing.GroupLayout(doacao_financeira);
        doacao_financeira.setLayout(doacao_financeiraLayout);
        doacao_financeiraLayout.setHorizontalGroup(
            doacao_financeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doacao_financeiraLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forma_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doacao_financeiraLayout.setVerticalGroup(
            doacao_financeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doacao_financeiraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(doacao_financeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(doacao_financeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(forma_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(doacao_financeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        item_material.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Descrição:");

        jScrollPane2.setViewportView(descricao);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Estado de conservação: ");

        estado_conservacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novo", "Semi-novo", "Usado" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Estimativa de valor: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Quantidade:");

        quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        estimativa_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout item_materialLayout = new javax.swing.GroupLayout(item_material);
        item_material.setLayout(item_materialLayout);
        item_materialLayout.setHorizontalGroup(
            item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item_materialLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(item_materialLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado_conservacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(item_materialLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(item_materialLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estimativa_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        item_materialLayout.setVerticalGroup(
            item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item_materialLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estado_conservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item_materialLayout.createSequentialGroup()
                        .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(item_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item_materialLayout.createSequentialGroup()
                        .addComponent(estimativa_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        trabalho_voluntario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trabalho Voluntário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Data de ínicio:");

        jScrollPane5.setViewportView(data_inicio);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Data final:");

        jScrollPane6.setViewportView(data_final);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Turno:");

        turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Dias da semana:");

        domingo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        domingo.setText("Domingo");
        domingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domingoActionPerformed(evt);
            }
        });

        segunda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        segunda.setText("Segunda");

        terça.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        terça.setText("Terça");

        quarta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quarta.setText("Quarta");

        quinta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quinta.setText("Quinta");

        sexta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexta.setText("Sexta");

        sabado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sabado.setText("Sábado");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Descrição do trabalho:");

        descricao_servico.setViewportView(txtDescricao_servico);

        javax.swing.GroupLayout trabalho_voluntarioLayout = new javax.swing.GroupLayout(trabalho_voluntario);
        trabalho_voluntario.setLayout(trabalho_voluntarioLayout);
        trabalho_voluntarioLayout.setHorizontalGroup(
            trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricao_servico))))
                    .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(domingo)
                        .addGap(26, 26, 26)
                        .addComponent(segunda)
                        .addGap(18, 18, 18)
                        .addComponent(terça)
                        .addGap(18, 18, 18)
                        .addComponent(quarta)
                        .addGap(18, 18, 18)
                        .addComponent(quinta)
                        .addGap(18, 18, 18)
                        .addComponent(sexta)
                        .addGap(18, 18, 18)
                        .addComponent(sabado)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        trabalho_voluntarioLayout.setVerticalGroup(
            trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trabalho_voluntarioLayout.createSequentialGroup()
                .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(descricao_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(trabalho_voluntarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domingo)
                    .addComponent(segunda)
                    .addComponent(terça)
                    .addComponent(quarta)
                    .addComponent(quinta)
                    .addComponent(sexta)
                    .addComponent(sabado))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        orgem_doacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Origem da doação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup2.add(opc_campanha);
        opc_campanha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opc_campanha.setText("Campanha");
        opc_campanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_campanhaActionPerformed(evt);
            }
        });

        buttonGroup2.add(opc_doador);
        opc_doador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opc_doador.setText("Doador");
        opc_doador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_doadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orgem_doacaoLayout = new javax.swing.GroupLayout(orgem_doacao);
        orgem_doacao.setLayout(orgem_doacaoLayout);
        orgem_doacaoLayout.setHorizontalGroup(
            orgem_doacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgem_doacaoLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(opc_campanha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(opc_doador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        orgem_doacaoLayout.setVerticalGroup(
            orgem_doacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgem_doacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orgem_doacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opc_campanha)
                    .addComponent(opc_doador))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_campanha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camapanha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Seleciona e a campanha:");

        comboCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampanhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_campanhaLayout = new javax.swing.GroupLayout(panel_campanha);
        panel_campanha.setLayout(panel_campanhaLayout);
        panel_campanhaLayout.setHorizontalGroup(
            panel_campanhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_campanhaLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panel_campanhaLayout.setVerticalGroup(
            panel_campanhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_campanhaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_campanhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_doador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Selecione o doador: ");

        javax.swing.GroupLayout panel_doadorLayout = new javax.swing.GroupLayout(panel_doador);
        panel_doador.setLayout(panel_doadorLayout);
        panel_doadorLayout.setHorizontalGroup(
            panel_doadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doadorLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboDador, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_doadorLayout.setVerticalGroup(
            panel_doadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doadorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_doadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboDador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setText("Salvar Doação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButton2.setText("Limpar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data da Doação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Data:");

        data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doacao_financeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(item_material, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trabalho_voluntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orgem_doacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_campanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_doador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doacao_financeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trabalho_voluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orgem_doacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_campanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_doador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void domingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domingoActionPerformed

    private void opc_campanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_campanhaActionPerformed
        // TODO add your handling code here:
        panel_campanha.setVisible(true);
        panel_doador.setVisible(false);
        pack();
    }//GEN-LAST:event_opc_campanhaActionPerformed

    private void slct_doacao_finaceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slct_doacao_finaceiraActionPerformed
        // TODO add your handling code here:
        doacao_financeira.setVisible(true);
        trabalho_voluntario.setVisible(false);
        item_material.setVisible(false);
        pack();
    }//GEN-LAST:event_slct_doacao_finaceiraActionPerformed

    private void slct_trabalho_volunatrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slct_trabalho_volunatrioActionPerformed
        // TODO add your handling code here:
        trabalho_voluntario.setVisible(true);
        doacao_financeira.setVisible(false);
        item_material.setVisible(false);
        pack();
        
    }//GEN-LAST:event_slct_trabalho_volunatrioActionPerformed

    private void slct_item_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slct_item_materialActionPerformed
        // TODO add your handling code here:
        item_material.setVisible(true);
        doacao_financeira.setVisible(false);
        trabalho_voluntario.setVisible(false);
        pack();
        
    }//GEN-LAST:event_slct_item_materialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        DoacaoDAO doacaoDAO = new DoacaoDAO();
        DiaSemanaVoluntarioDAO diaSemanaVoluntarioDAO = new DiaSemanaVoluntarioDAO();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate objData;
        Integer id_campanha =null;
        Integer id_doador = null;



        // Lógica para obter a data
        try {
            objData = LocalDate.parse(data.getText(), formatter);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "O campo 'Data' é obrigatório e deve estar no formato dd/MM/yyyy.");
            return;
        }

// 2. Lógica para determinar a origem da doação (exclusiva)
        if (opc_campanha.isSelected()) {
            // Se a origem é uma campanha, o doador não é obrigatório
            ComboAuxiliar campanhaSelecionada = (ComboAuxiliar) comboCampanha.getSelectedItem();
            if (campanhaSelecionada != null) {
                id_campanha = campanhaSelecionada.getId_doador();
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma campanha para a doação.");
                return;
            }
        } else if (opc_doador.isSelected()) {
            // Se a origem é um doador, o doador é obrigatório e não há campanha
            ComboAuxiliar doadorSelecionado = (ComboAuxiliar) comboDador.getSelectedItem();
            if (doadorSelecionado != null) {
                id_doador = doadorSelecionado.getId_doador();
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um doador para a doação.");
                return;
            }
        } else {
            // Nenhuma origem foi selecionada
            JOptionPane.showMessageDialog(this, "Selecione a origem da doação: Doador ou Campanha.");
            return;
        }

        try {
            if (slct_doacao_finaceira.isSelected()) {
                String objTipo_doacao = "Doação Financeira";
                float objValor_total;

                if (valor_total.getText().isBlank()) {
                    JOptionPane.showMessageDialog(this, "Preencha o campo 'Valor total'.");
                    return;
                }
                try {
                    objValor_total = Float.parseFloat(valor_total.getText().replace(",", "."));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "O campo 'Valor total' deve ser um número válido.");
                    return;
                }

                String objForma_pagamento = (String) forma_pagamento.getSelectedItem();
                DoacaoFinanceiraDTO doacaoFinanceiraDTO = new DoacaoFinanceiraDTO(objData, objTipo_doacao, 0, id_doador, id_campanha, objForma_pagamento, objValor_total);
                doacaoDAO.cadastrarDoacao(doacaoFinanceiraDTO);

            } else if (slct_item_material.isSelected()) {
                String objTipo_doacao = "Doação de Item Material";
                String objDescricao = descricao.getText();
                String objEstado_conservacao = (String) estado_conservacao.getSelectedItem();
                float objEstimativa_valor;
                int objQuantidade;

                if (objDescricao.isBlank()) {
                    JOptionPane.showMessageDialog(this, "Preencha a 'Descrição'.");
                    return;
                }

                try {
                    objQuantidade = Integer.parseInt(quantidade.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "O campo 'Quantidade' deve ser um número inteiro.");
                    return;
                }
                if (objQuantidade <= 0) {
                    JOptionPane.showMessageDialog(this, "A 'Quantidade' deve ser maior que zero.");
                    return;
                }

                try {
                    objEstimativa_valor = Float.parseFloat(estimativa_valor.getText().replace(",", "."));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "O campo 'Estimativa de valor' deve ser um número válido.");
                    return;
                }

                DoacaoItemMaterialDTO doacaoMaterial = new DoacaoItemMaterialDTO(objData, objTipo_doacao, 0, id_doador, id_campanha, objDescricao, objEstado_conservacao, objQuantidade, objEstimativa_valor);
                doacaoDAO.cadastrarDoacao(doacaoMaterial);

            } else if (slct_trabalho_volunatrio.isSelected()) {
                String tipo_doacao = "Trabalho Voluntário";
                LocalDate objData_inicio, objData_final;

                try {
                    objData_inicio = LocalDate.parse(data_inicio.getText(), formatter);
                    objData_final = LocalDate.parse(data_final.getText(), formatter);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "As datas de 'Trabalho Voluntário' são obrigatórias e devem estar no formato dd/MM/yyyy.");
                    return;
                }

                String objDescricao_servico = txtDescricao_servico.getText();
                String objTurno = (String) turno.getSelectedItem();

                TrabalhoVoluntarioDTO trabalhoVoluntarioDTO = new TrabalhoVoluntarioDTO(objData, tipo_doacao, 0, id_doador, id_campanha, objDescricao_servico, objData_inicio, objData_final);
                doacaoDAO.cadastrarDoacao(trabalhoVoluntarioDTO);

                // Lógica para cadastrar a disponibilidade para cada dia selecionado
                if (domingo.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Domingo", objTurno));
                }
                if (segunda.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Segunda", objTurno));
                }
                if (terça.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Terça", objTurno));
                }
                if (quarta.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Quarta", objTurno));
                }
                if (quinta.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Quinta", objTurno));
                }
                if (sexta.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Sexta", objTurno));
                }
                if (sabado.isSelected()) {
                    diaSemanaVoluntarioDAO.cadastrarDisponibilidade(new DiaSemanaVoluntarioDTO(0, id_doador, "Sábado", objTurno));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um tipo de doação.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Doação cadastrada com Sucesso!");
            limparCampos();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar a doação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }                                        

    

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void comboCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampanhaActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_comboCampanhaActionPerformed

    private void opc_doadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_doadorActionPerformed
        // TODO add your handling code here:
        panel_campanha.setVisible(false);
        panel_doador.setVisible(true);
        pack();
    }//GEN-LAST:event_opc_doadorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void limparCampos(){
         data.setText("");
    valor_total.setText("");
    descricao.setText("");
    estimativa_valor.setText("");
    quantidade.setText("");
    data_inicio.setText("");
    data_final.setText("");
    txtDescricao_servico.setText("");

    // Combos
    if (forma_pagamento.getItemCount() > 0) forma_pagamento.setSelectedIndex(0);
    if (turno.getItemCount() > 0) turno.setSelectedIndex(0);
    if (comboDador.getItemCount() > 0) comboDador.setSelectedIndex(0);
    if (comboCampanha.getItemCount() > 0) comboCampanha.setSelectedIndex(0);

    // Checkboxes de dias da semana
    domingo.setSelected(false);
    segunda.setSelected(false);
    terça.setSelected(false);
    quarta.setSelected(false);
    quinta.setSelected(false);
    sexta.setSelected(false);
    sabado.setSelected(false);

    // Radio buttons (agrupados)
    slct_doacao_finaceira.setSelected(false);
    slct_item_material.setSelected(false);
    slct_trabalho_volunatrio.setSelected(false);

    // Opcões de filtro de campanha e doador
    opc_campanha.setSelected(false);
    opc_doador.setSelected(false);
    }    
    private void carregarCampanhas() {
        DefaultComboBoxModel<ComboAuxiliar> combo_Campanha = new DefaultComboBoxModel<>();
        ConexaoMySQL con = new ConexaoMySQL();

        try (Connection cnn = con.getConnection()) {
            String sql = "SELECT *FROM campanha";
            PreparedStatement pst = cnn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String nome  = rs.getString("nome_campanha");
                int id = rs.getInt("id_campanha");

                combo_Campanha.addElement(new ComboAuxiliar(id, nome));
            }

            comboCampanha.setModel(combo_Campanha);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar campanhas: " + e.getMessage());
        }
    }
        private void carregarDoadores() {
    DefaultComboBoxModel<ComboAuxiliar> combo_Doador = new DefaultComboBoxModel<>();
    ConexaoMySQL con = new ConexaoMySQL();

    try (Connection cnn = con.getConnection()) {
        String sql =
            "SELECT *FROM doadaor_pessoafisica_pessoajuridica " ;


        PreparedStatement pst = cnn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
          String nome=  rs.getString("nome_completo") !=null ? rs.getString("nome_completo") : rs.getString("nome_empresa");


           int id= rs.getInt("id_doador");
            combo_Doador.addElement(new ComboAuxiliar(id,nome));
        }

        comboDador.setModel(combo_Doador);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar doadores: " + e.getMessage());
    }
}

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new javax.swing.plaf.metal.OceanTheme());

        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            TelaCadastroDoacao tela = new TelaCadastroDoacao();
            tela.pack(); // Ajusta os tamanhos dos componentes conforme o layout
            tela.setLocationRelativeTo(null); // Centraliza na tela
            tela.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private JComboBox<ComboAuxiliar> comboCampanha;
    private JComboBox<ComboAuxiliar> comboDador;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextPane data_final;
    private javax.swing.JTextPane data_inicio;
    private javax.swing.JTextPane descricao;
    private javax.swing.JScrollPane descricao_servico;
    private javax.swing.JPanel doacao_financeira;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JComboBox<String> estado_conservacao;
    private javax.swing.JFormattedTextField estimativa_valor;
    private javax.swing.JComboBox<String> forma_pagamento;
    private javax.swing.JPanel item_material;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton opc_campanha;
    private javax.swing.JRadioButton opc_doador;
    private javax.swing.JPanel orgem_doacao;
    private javax.swing.JPanel panel_campanha;
    private javax.swing.JPanel panel_doador;
    private javax.swing.JFormattedTextField quantidade;
    private javax.swing.JCheckBox quarta;
    private javax.swing.JCheckBox quinta;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JCheckBox segunda;
    private javax.swing.JCheckBox sexta;
    private javax.swing.JRadioButton slct_doacao_finaceira;
    private javax.swing.JRadioButton slct_item_material;
    private javax.swing.JRadioButton slct_trabalho_volunatrio;
    private javax.swing.JCheckBox terça;
    private javax.swing.JPanel trabalho_voluntario;
    private javax.swing.JComboBox<String> turno;
    private javax.swing.JTextPane txtDescricao_servico;
    private javax.swing.JTextPane valor_total;
    // End of variables declaration//GEN-END:variables
}
