/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View;

import org.example.DAO.DoadorDAO;
import org.example.DTO.PessoaFisicaDTO;
import org.example.DTO.PessoaJuridicaDTO;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author Estella1
 */
public class TelaCadastroDoador extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDoador
     */
    public TelaCadastroDoador() {
        initComponents();
        pack(); // ajusta o tamanho da janela com base no layout
        setLocationRelativeTo(null);
        pessoa_fisica.setSelected(true);
        pessoa_fisicaActionPerformed(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pessoa_fisica = new javax.swing.JRadioButton();
        pessoa_juridica = new javax.swing.JRadioButton();
        dados_pessoais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nome_contato2 = new javax.swing.JScrollPane();
        nome = new javax.swing.JTextPane();
        nome1 = new javax.swing.JLabel();
        nome_contato3 = new javax.swing.JScrollPane();
        cpf = new javax.swing.JTextPane();
        nome2 = new javax.swing.JLabel();
        nome_contato4 = new javax.swing.JScrollPane();
        rg = new javax.swing.JTextPane();
        dados_empresa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome_contato = new javax.swing.JScrollPane();
        cnpj = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        nome_empresa = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        razao_social = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JScrollPane();
        telefone1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        pref_contato = new javax.swing.JLabel();
        telefone3 = new javax.swing.JScrollPane();
        email1 = new javax.swing.JTextPane();
        preferencia_meio_contato = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logradouro = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        complemento1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        cidade = new javax.swing.JTextPane();
        numero = new javax.swing.JScrollPane();
        numero_end = new javax.swing.JTextPane();
        numero1 = new javax.swing.JScrollPane();
        bairro = new javax.swing.JTextPane();
        estado = new javax.swing.JComboBox<>();
        limpar_campos = new javax.swing.JButton();
        salvar_cadastro1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        frequencia_doacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Novo Doador");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Doador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        buttonGroup1.add(pessoa_fisica);
        pessoa_fisica.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        pessoa_fisica.setText("Pessoa Física");
        pessoa_fisica.setToolTipText("");
        pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoa_fisicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(pessoa_juridica);
        pessoa_juridica.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        pessoa_juridica.setText("Pessoa Jurídica");
        pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoa_juridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pessoa_juridica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoa_fisica)
                    .addComponent(pessoa_juridica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dados_pessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Nome completo:");

        nome_contato2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome.setSelectionColor(new java.awt.Color(0, 0, 0));
        nome_contato2.setViewportView(nome);

        nome1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        nome1.setText("CPF:");

        cpf.setSelectionColor(new java.awt.Color(0, 0, 0));
        nome_contato3.setViewportView(cpf);

        nome2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        nome2.setText("RG:");

        rg.setSelectionColor(new java.awt.Color(0, 0, 0));
        nome_contato4.setViewportView(rg);

        javax.swing.GroupLayout dados_pessoaisLayout = new javax.swing.GroupLayout(dados_pessoais);
        dados_pessoais.setLayout(dados_pessoaisLayout);
        dados_pessoaisLayout.setHorizontalGroup(
            dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nome1)
                    .addComponent(nome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_contato4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nome_contato3)
                        .addComponent(nome_contato2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        dados_pessoaisLayout.setVerticalGroup(
            dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_contato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome1)
                    .addComponent(nome_contato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_contato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome2))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        dados_empresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Nome da empresa:");

        cnpj.setSelectionColor(new java.awt.Color(0, 0, 0));
        nome_contato.setViewportView(cnpj);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("CNPJ :");

        label4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label4.setText("Razão social:");
        label4.setToolTipText("");

        nome_empresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nome_empresa.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(nome_empresa);

        razao_social.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(razao_social);

        javax.swing.GroupLayout dados_empresaLayout = new javax.swing.GroupLayout(dados_empresa);
        dados_empresa.setLayout(dados_empresaLayout);
        dados_empresaLayout.setHorizontalGroup(
            dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_empresaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(dados_empresaLayout.createSequentialGroup()
                        .addComponent(label4)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane6))
                    .addGroup(dados_empresaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(nome_contato)))
                .addContainerGap())
        );
        dados_empresaLayout.setVerticalGroup(
            dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_empresaLayout.createSequentialGroup()
                        .addGroup(dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(dados_empresaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(nome_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meios de Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Telefone:");

        telefone.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        telefone1.setSelectionColor(new java.awt.Color(0, 0, 0));
        telefone.setViewportView(telefone1);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Email:");

        pref_contato.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        pref_contato.setText("Pref.Contato:");

        telefone3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        email1.setSelectionColor(new java.awt.Color(0, 0, 0));
        telefone3.setViewportView(email1);

        preferencia_meio_contato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefone", "Email", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(telefone))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(pref_contato))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preferencia_meio_contato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefone3))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(pref_contato)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(telefone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preferencia_meio_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Logradouro:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Complemento:");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Número:");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Bairro:");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Estado:");

        jScrollPane2.setViewportView(logradouro);

        jScrollPane3.setViewportView(complemento1);

        jScrollPane4.setViewportView(cidade);

        numero.setViewportView(numero_end);

        numero1.setViewportView(bairro);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel11)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        limpar_campos.setText("Limpar Campos");
        limpar_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_camposActionPerformed(evt);
            }
        });

        salvar_cadastro1.setText("Salvar Cadastro");
        salvar_cadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_cadastro1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Freqência de Doação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("Frequência:");

        frequencia_doacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Única", "Bimestral", "Trimestral", "Semestral", "Anual" }));
        frequencia_doacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencia_doacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frequencia_doacao, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(frequencia_doacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dados_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dados_pessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salvar_cadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dados_pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dados_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpar_campos)
                    .addComponent(salvar_cadastro1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_estadoActionPerformed

    private void pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoa_fisicaActionPerformed
        // TODO add your handling code here:
        dados_pessoais.setVisible(true);
        dados_empresa.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_pessoa_fisicaActionPerformed

    private void salvar_cadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_cadastro1ActionPerformed
        // TODO add your handling code here:
        DoadorDAO doadorDAO = new DoadorDAO();

        String obgjEmail = email1.getText();
        String objTelefone = telefone1.getText();
        String objFrequencia = (String) frequencia_doacao.getSelectedItem();
        String objLogradouro = logradouro.getText();
        String objBairro = bairro.getText();
        String objCidade = cidade.getText();
        String objEstado = (String) estado.getSelectedItem();
        String numeroString = numero_end.getText();
        String objComplemento = complemento1.getText();
        String objPreferencia_meio_contato = (String) preferencia_meio_contato.getSelectedItem();
        // Adicionando coleta de CEP - ATENÇÃO: Se não houver campo txtCep no Design, dará erro.
        String objCep = ""; // Inicialize ou colete de um componente como txtCep.getText();
        // Se você não tem um JTextPane/JTextField para CEP no seu design,
        // remova objCep dos construtores DTO ou adicione o campo.

        int objNumero = 0;
        try{
            objNumero = Integer.parseInt(numeroString);
        }catch(NumberFormatException e){
            System.out.println("O valor do núemro não é um inteiro");
            JOptionPane.showMessageDialog(this, "O campo 'Número' deve conter apenas dígitos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (objLogradouro.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Logradouro' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objBairro.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Bairro' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objCidade.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Cidade' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objEstado == null || objEstado.trim().isEmpty() || objEstado.equals("Selecione o Estado")) {
            JOptionPane.showMessageDialog(this, "O campo 'Estado' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objTelefone.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Telefone' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (obgjEmail.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Email' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objFrequencia == null || objFrequencia.trim().isEmpty() || objFrequencia.equals("Selecione a Frequência")) {
            JOptionPane.showMessageDialog(this, "O campo 'Frequência de Doação' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validação para CEP, se o campo for adicionado
        // if (objCep.trim().isEmpty()) {
        //     JOptionPane.showMessageDialog(this, "O campo 'CEP' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        //     return;
        // }


        if (pessoa_fisica.isSelected()){
            String objTipo_doador = "Pessoa Física";
            String objNome = nome.getText();
            String objCPF = cpf.getText();
            String objRG = rg.getText();

            if (objNome.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'Nome' é obrigatório para Pessoa Física.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (objCPF.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'CPF' é obrigatório para Pessoa Física.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (objRG.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'RG' é obrigatório para Pessoa Física.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PessoaFisicaDTO pessoaFisica = new PessoaFisicaDTO(
                    objTipo_doador, objPreferencia_meio_contato, objComplemento, objNumero,
                    objEstado, objCidade, objBairro, objLogradouro,
                    objFrequencia, objTelefone, obgjEmail, 0, // id_doador (gerado pelo banco)
                    objRG, objCPF, objNome // Parâmetros específicos de PF
                    // Se CEP estiver no construtor de PessoaFisicaDTO, adicione aqui: , objCep
            );
            try{
                doadorDAO.cadastrarDoador(pessoaFisica);
                JOptionPane.showMessageDialog(this, "Cadastro de Doador feito com sucesso",
                        "Cadastro conluido!", JOptionPane.INFORMATION_MESSAGE);

                limpar_camposActionPerformed(null);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao cadastrar Pessoa Física", JOptionPane.ERROR_MESSAGE);
            }

        }else if(pessoa_juridica.isSelected()){
            String objTipo_doador = "Pessoa Jurídica";
            String objNome_contato = nome_empresa.getText();
            String objRazao_social = razao_social.getText();
            String objCNPJ = cnpj.getText();

            if (objNome_contato.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'Nome do Contato' é obrigatório para Pessoa Jurídica.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (objCNPJ.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'CNPJ' é obrigatório para Pessoa Jurídica.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (objRazao_social.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'Razão Social' é obrigatório para Pessoa Jurídica.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PessoaJuridicaDTO pessoaJuridica = new PessoaJuridicaDTO(
                    objTipo_doador, objPreferencia_meio_contato, objComplemento, objNumero,
                    objEstado, objCidade, objBairro, objLogradouro,
                    objFrequencia, objTelefone, obgjEmail, 0, // id_doador
                    objNome_contato, objCNPJ, objRazao_social // Parâmetros específicos de PJ
                    // Se CEP estiver no construtor de PessoaJuridicaDTO, adicione aqui: , objCep
            );

            try{
                doadorDAO.cadastrarDoador(pessoaJuridica);
                JOptionPane.showMessageDialog(this, "Cadastro de Doador feito com sucesso",
                        "Cadastro conluido!", JOptionPane.INFORMATION_MESSAGE);

                limpar_camposActionPerformed(null);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,e.getMessage(),"Erro ao cadastrar Pessoa Juridica", JOptionPane.ERROR_MESSAGE);
            }


        }else {
            // Se nenhum tipo de doador foi selecionado
            JOptionPane.showMessageDialog(this, "Selecione o tipo de doador (Pessoa Física ou Jurídica).", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_salvar_cadastro1ActionPerformed

    private void pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoa_juridicaActionPerformed
        // TODO add your handling code here:
        dados_pessoais.setVisible(false);
        dados_empresa.setVisible(true);
        
    }//GEN-LAST:event_pessoa_juridicaActionPerformed

    private void limpar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_camposActionPerformed
        // TODO add your handling code here:
        email1.setText("");
        telefone1.setText("");
        frequencia_doacao.setSelectedIndex(0);
        logradouro.setText("");
        bairro.setText("");
        cidade.setText("");
        estado.setSelectedIndex(0);
        numero_end.setText("");
        complemento1.setText("");
        preferencia_meio_contato.setSelectedIndex(0);

        // Limpar campos PF
        nome.setText("");
        cpf.setText("");
        rg.setText("");

        // Limpar campos PJ
        nome_empresa.setText("");
        razao_social.setText("");
        cnpj.setText("");
    }//GEN-LAST:event_limpar_camposActionPerformed

    private void frequencia_doacaoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
       
    }

    public void run(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new javax.swing.plaf.metal.OceanTheme());

        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            TelaCadastroDoador tela = new TelaCadastroDoador();
            tela.pack(); // Ajusta os tamanhos dos componentes conforme o layout
            tela.setLocationRelativeTo(null); // Centraliza na tela
            tela.setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane bairro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextPane cidade;
    private javax.swing.JTextPane cnpj;
    private javax.swing.JTextPane complemento1;
    private javax.swing.JTextPane cpf;
    private javax.swing.JPanel dados_empresa;
    private javax.swing.JPanel dados_pessoais;
    private javax.swing.JTextPane email1;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JComboBox<String> frequencia_doacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel label4;
    private javax.swing.JButton limpar_campos;
    private javax.swing.JTextPane logradouro;
    private javax.swing.JTextPane nome;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome2;
    private javax.swing.JScrollPane nome_contato;
    private javax.swing.JScrollPane nome_contato2;
    private javax.swing.JScrollPane nome_contato3;
    private javax.swing.JScrollPane nome_contato4;
    private javax.swing.JTextPane nome_empresa;
    private javax.swing.JScrollPane numero;
    private javax.swing.JScrollPane numero1;
    private javax.swing.JTextPane numero_end;
    private javax.swing.JRadioButton pessoa_fisica;
    private javax.swing.JRadioButton pessoa_juridica;
    private javax.swing.JLabel pref_contato;
    private javax.swing.JComboBox<String> preferencia_meio_contato;
    private javax.swing.JTextPane razao_social;
    private javax.swing.JTextPane rg;
    private javax.swing.JButton salvar_cadastro1;
    private javax.swing.JScrollPane telefone;
    private javax.swing.JTextPane telefone1;
    private javax.swing.JScrollPane telefone3;
    // End of variables declaration//GEN-END:variables
}
